version: '3.8'

services:
  prediction-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - MODEL_PATH=./models/heat_disease_prediction.h5
    volumes:
      - ./models:/app/models
    restart: unless-stopped