# ===============================
# NestJS dev mode with hot reload
# ===============================

FROM node:20-alpine

WORKDIR /app

# Copy file package
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8082

CMD ["npm", "run", "start:dev"]
