# ===============================
# NestJS dev mode with hot reload
# ===============================

FROM node:20-alpine

# Tạo thư mục làm việc
WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .

EXPOSE 8084

CMD ["npm", "run", "start:dev"]
